version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
      - WALLET_CONFIGURED=true
      - SOLANA_NETWORK=devnet
      - SOLANA_URL=https://api.devnet.solana.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/certificados/info-rede"]
      interval: 30s
      timeout: 10s
      retries: 3
